before_install:
  - 'gem install bundler:1.16.1'
jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo test
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: sf-stages-staging
        api_key: $HEROKU_AUTH_TOKEN
        on: sf-stages-demo
    - stage: test staging
      script: 'curl http://sf-stages-staging.herokuapp.com'

    - stage: test production
      script: 'curl http://sf-stages-production.herokuapp.com'